export const REMOVE_FROM_PRODUCT_LIST ='REMOVE_FROM_PRODUCT_LIST';
export const GET_PRODUCT_LIST_REQUEST ='GET_PRODUCT_LIST_REQUEST';
export const GET_PRODUCT_LIST_SUCCESS ='GET_PRODUCT_LIST_SUCCESS';
export const GET_PRODUCT_LIST_REJECTED ='GET_PRODUCT_LIST_REJECTED'; 